# Generated by Django 5.2.1 on 2025-06-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_replace_elevenlabs_with_google_cloud_tts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationalbot',
            name='voice_name',
            field=models.CharField(default='en-US-Studio-O', help_text='Google Cloud Text-to-Speech voice name', max_length=100),
        ),
        migrations.AlterField(
            model_name='googlecloudttsusage',
            name='characters_limit',
            field=models.IntegerField(default=10000),
        ),
    ]
